#! /bin/bash
# Script generated by przyp.sh
#

p_IMG_FORUM=/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/01-B4350718-0EF3-48A1-B594-C89107C1ABEF Planete_HD 17-00 ° 8_PICTURE_FORUM.png
export DISPLAY=:0 && yad --title "° Świat bez granic     Indie Magia latawców serial dokumentalny Francja " \
   --on-top --sticky --center \
   --borders=5 \
   --timeout=1200 \
   --timeout-indicator=bottom \
   --image "/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/01-B4350718-0EF3-48A1-B594-C89107C1ABEF Planete_HD 17-00 ° 8_PICTURE_FORUM.png" \
   --button=gtk-quit\:1 &
exit 0
