#! /bin/bash
# Script generated by przyp.sh
#

paplay --volume=20000 "/home/rysio/Pobrane/PROGRAM_TV_ZEE/przypominajka.ogg" &
export DISPLAY=:0 && yad --title "° Świat bez granic     Indie Magia latawców serial dokumentalny Francja " \
   --on-top --sticky --center \
   --borders=5 \
   --timeout=1200 \
   --timeout-indicator=bottom \
   --image "/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/01-B4350718-0EF3-48A1-B594-C89107C1ABEF Planete_HD 17-00 ° 7_PICTURE_OUT.png" \
   --button="Otwórz obrazki"!gtk-ok\:"/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/01-B4350718-0EF3-48A1-B594-C89107C1ABEF_PIC.sh" \
   --button="Otwórz forum"!gtk-ok\:"/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/01-B4350718-0EF3-48A1-B594-C89107C1ABEF_FORUM.sh" \
   --button="Otwórz URL"!gtk-ok\:"/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/01-B4350718-0EF3-48A1-B594-C89107C1ABEF_URL.sh" \
   --button=gtk-quit\:1 &
