#! /bin/bash
# Script generated by przyp.sh
#

p_IMG_FORUM=/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/02-286E5EDC-2252-4034-85A0-4C251361C38B CBS_Europa_HD 17-10 TONI 8_PICTURE_FORUM.png
export DISPLAY=:0 && yad --title "Toni Braxton nie łam mi serca dramat biograficzny USA 2016 ^^^" \
   --on-top --sticky --center \
   --borders=5 \
   --timeout=1200 \
   --timeout-indicator=bottom \
   --image "/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/02-286E5EDC-2252-4034-85A0-4C251361C38B CBS_Europa_HD 17-10 TONI 8_PICTURE_FORUM.png" \
   --button=gtk-quit\:1 &
exit 0
