#! /bin/bash
# Script generated by przyp.sh
#

p_IMG_FORUM=/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/03-8E6AFFB7-C19D-42FE-BA06-767B9BEC5A67 Cinemax2 17-20 TITANIC 8_PICTURE_FORUM.png
export DISPLAY=:0 && yad --title "Titanic dramat katastroficzny USA 1997 ^^^^^" \
   --on-top --sticky --center \
   --borders=5 \
   --timeout=1200 \
   --timeout-indicator=bottom \
   --image "/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/03-8E6AFFB7-C19D-42FE-BA06-767B9BEC5A67 Cinemax2 17-20 TITANIC 8_PICTURE_FORUM.png" \
   --button=gtk-quit\:1 &
exit 0
