#! /bin/bash
# Script generated by przyp.sh
#

paplay --volume=20000 "/home/rysio/Pobrane/PROGRAM_TV_ZEE/przypominajka.ogg" &
export DISPLAY=:0 && yad --title "Titanic dramat katastroficzny USA 1997 ^^^^^" \
   --on-top --sticky --center \
   --borders=5 \
   --timeout=1200 \
   --timeout-indicator=bottom \
   --image "/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/03-8E6AFFB7-C19D-42FE-BA06-767B9BEC5A67 Cinemax2 17-20 TITANIC 7_PICTURE_OUT.png" \
   --button="Otwórz obrazki"!gtk-ok\:"/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/03-8E6AFFB7-C19D-42FE-BA06-767B9BEC5A67_PIC.sh" \
   --button="Otwórz forum"!gtk-ok\:"/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/03-8E6AFFB7-C19D-42FE-BA06-767B9BEC5A67_FORUM.sh" \
   --button="Otwórz URL"!gtk-ok\:"/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/03-8E6AFFB7-C19D-42FE-BA06-767B9BEC5A67_URL.sh" \
   --button=gtk-quit\:1 &
