#! /bin/bash
# Script generated by przyp.sh
#

p_IMG_FORUM=/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/04-0AC711EF-26D2-400D-8DA0-22312A4F5F71 TVN_Fabuła 17-25 WIELKI 8_PICTURE_FORUM.png
export DISPLAY=:0 && yad --title "Wielki Mike film obyczajowy USA 2009 ^^^^" \
   --on-top --sticky --center \
   --borders=5 \
   --timeout=1200 \
   --timeout-indicator=bottom \
   --image "/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/04-0AC711EF-26D2-400D-8DA0-22312A4F5F71 TVN_Fabuła 17-25 WIELKI 8_PICTURE_FORUM.png" \
   --button=gtk-quit\:1 &
exit 0
