#! /bin/bash
# Script generated by przyp.sh
#

paplay --volume=20000 "/home/rysio/Pobrane/PROGRAM_TV_ZEE/przypominajka.ogg" &
export DISPLAY=:0 && yad --title "Wielki Mike film obyczajowy USA 2009 ^^^^" \
   --on-top --sticky --center \
   --borders=5 \
   --timeout=1200 \
   --timeout-indicator=bottom \
   --image "/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/04-0AC711EF-26D2-400D-8DA0-22312A4F5F71 TVN_Fabuła 17-25 WIELKI 7_PICTURE_OUT.png" \
   --button="Otwórz obrazki"!gtk-ok\:"/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/04-0AC711EF-26D2-400D-8DA0-22312A4F5F71_PIC.sh" \
   --button="Otwórz forum"!gtk-ok\:"/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/04-0AC711EF-26D2-400D-8DA0-22312A4F5F71_FORUM.sh" \
   --button="Otwórz URL"!gtk-ok\:"/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/04-0AC711EF-26D2-400D-8DA0-22312A4F5F71_URL.sh" \
   --button=gtk-quit\:1 &
