#! /bin/bash
# Script generated by przyp.sh
#

p_IMG_FORUM=/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/05-9FA1CA3D-0E92-4E02-ADFE-80E926A9564B HBO 17-35 CÓŻ 8_PICTURE_FORUM.png
export DISPLAY=:0 && yad --title "Cóż za piękny dzień dramat biograficzny USA 2019 ^^^" \
   --on-top --sticky --center \
   --borders=5 \
   --timeout=1200 \
   --timeout-indicator=bottom \
   --image "/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/05-9FA1CA3D-0E92-4E02-ADFE-80E926A9564B HBO 17-35 CÓŻ 8_PICTURE_FORUM.png" \
   --button=gtk-quit\:1 &
exit 0
