#! /bin/bash
# Script generated by przyp.sh
#

paplay --volume=20000 "/home/rysio/Pobrane/PROGRAM_TV_ZEE/przypominajka.ogg" &
export DISPLAY=:0 && yad --title "Pokémon Detektyw Pikachu film fantasy Kanada 2019 ^^^" \
   --on-top --sticky --center \
   --borders=5 \
   --timeout=1200 \
   --timeout-indicator=bottom \
   --image "/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/06-5921D23E-1C51-47C6-8E0E-8667E9DBB492 HBO3 17-40 POKÉMON 7_PICTURE_OUT.png" \
   --button="Otwórz obrazki"!gtk-ok\:"/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/06-5921D23E-1C51-47C6-8E0E-8667E9DBB492_PIC.sh" \
   --button="Otwórz forum"!gtk-ok\:"/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/06-5921D23E-1C51-47C6-8E0E-8667E9DBB492_FORUM.sh" \
   --button="Otwórz URL"!gtk-ok\:"/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/06-5921D23E-1C51-47C6-8E0E-8667E9DBB492_URL.sh" \
   --button=gtk-quit\:1 &
