#! /bin/bash
# Script generated by przyp.sh
#

p_IMG_FORUM=/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/06-5921D23E-1C51-47C6-8E0E-8667E9DBB492 HBO3 17-40 POKÉMON 8_PICTURE_FORUM.png
export DISPLAY=:0 && yad --title "Pokémon Detektyw Pikachu film fantasy Kanada 2019 ^^^" \
   --on-top --sticky --center \
   --borders=5 \
   --timeout=1200 \
   --timeout-indicator=bottom \
   --image "/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/06-5921D23E-1C51-47C6-8E0E-8667E9DBB492 HBO3 17-40 POKÉMON 8_PICTURE_FORUM.png" \
   --button=gtk-quit\:1 &
exit 0
