#! /bin/bash
# Script generated by przyp.sh
#

p_IMG_FORUM=/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/08-0E56554F-D410-4E12-9806-038010959968 BBC_Earth 17-55 OSTATNIE 8_PICTURE_FORUM.png
export DISPLAY=:0 && yad --title "Ostatnie zawody świata   film dokumentalny Wielka Brytania " \
   --on-top --sticky --center \
   --borders=5 \
   --timeout=1200 \
   --timeout-indicator=bottom \
   --image "/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/08-0E56554F-D410-4E12-9806-038010959968 BBC_Earth 17-55 OSTATNIE 8_PICTURE_FORUM.png" \
   --button=gtk-quit\:1 &
exit 0
