#! /bin/bash
# Script generated by przyp.sh
#

p_PIC=/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/08-0E56554F-D410-4E12-9806-038010959968 BBC_Earth 17-55 OSTATNIE 1_PICTURE_BIG.jpg
export DISPLAY=:0 && yad --title "Ostatnie zawody świata   film dokumentalny Wielka Brytania " \
   --on-top --sticky --center \
   --borders=5 \
   --timeout=1200 \
   --timeout-indicator=bottom \
   --image "/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/08-0E56554F-D410-4E12-9806-038010959968 BBC_Earth 17-55 OSTATNIE 1_PICTURE_BIG.jpg" \
   --button=gtk-quit\:1 &
exit 0
