#! /bin/bash
# Script generated by przyp.sh
#

p_PIC=/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/09-F7528EE0-94C2-4781-928A-62273DA59962 Cinemax 18-00 Z 1_PICTURE_BIG.jpg
export DISPLAY=:0 && yad --title "Z dala od zgiełku dramat obyczajowy USA 2015 ^^^" \
   --on-top --sticky --center \
   --borders=5 \
   --timeout=1200 \
   --timeout-indicator=bottom \
   --image "/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/09-F7528EE0-94C2-4781-928A-62273DA59962 Cinemax 18-00 Z 1_PICTURE_BIG.jpg" \
   --button=gtk-quit\:1 &
exit 0
