#! /bin/bash
# Script generated by przyp.sh
#

p_PIC=/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/10-9ED02AE6-5716-4250-9873-4F91A309CA7B Planete_HD 18-00 ŚWIAT 1_PICTURE_BIG.jpg
export DISPLAY=:0 && yad --title "Świat z góry     Anglia i Walia Od Symonds po serial dokumentalny Wielka Brytania " \
   --on-top --sticky --center \
   --borders=5 \
   --timeout=1200 \
   --timeout-indicator=bottom \
   --image "/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/10-9ED02AE6-5716-4250-9873-4F91A309CA7B Planete_HD 18-00 ŚWIAT 1_PICTURE_BIG.jpg" \
   --button=gtk-quit\:1 &
exit 0
