#! /bin/bash
# Script generated by przyp.sh
#

paplay --volume=20000 "/home/rysio/Pobrane/PROGRAM_TV_ZEE/przypominajka.ogg" &
export DISPLAY=:0 && yad --title "Miasto cieni dramat obyczajowy Islandia 2020 ^^^" \
   --on-top --sticky --center \
   --borders=5 \
   --timeout=1200 \
   --timeout-indicator=bottom \
   --image "/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/11-91EDDDCE-0070-4B6E-B2D4-E79419B10FD6 C+_Film 18-20 MIASTO 7_PICTURE_OUT.png" \
   --button="Otwórz obrazki"!gtk-ok\:"/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/11-91EDDDCE-0070-4B6E-B2D4-E79419B10FD6_PIC.sh" \
   --button="Otwórz forum"!gtk-ok\:"/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/11-91EDDDCE-0070-4B6E-B2D4-E79419B10FD6_FORUM.sh" \
   --button="Otwórz URL"!gtk-ok\:"/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/11-91EDDDCE-0070-4B6E-B2D4-E79419B10FD6_URL.sh" \
   --button=gtk-quit\:1 &
