#! /bin/bash
# Script generated by przyp.sh
#

p_IMG_FORUM=/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/11-91EDDDCE-0070-4B6E-B2D4-E79419B10FD6 C+_Film 18-20 MIASTO 8_PICTURE_FORUM.png
export DISPLAY=:0 && yad --title "Miasto cieni dramat obyczajowy Islandia 2020 ^^^" \
   --on-top --sticky --center \
   --borders=5 \
   --timeout=1200 \
   --timeout-indicator=bottom \
   --image "/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/11-91EDDDCE-0070-4B6E-B2D4-E79419B10FD6 C+_Film 18-20 MIASTO 8_PICTURE_FORUM.png" \
   --button=gtk-quit\:1 &
exit 0
