#! /bin/bash
# Script generated by przyp.sh
#

p_PIC=/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/12-D923F9F0-154B-4964-9F6E-715CF5858D8A POLSAT_Film 18-20 GRANICE 1_PICTURE_BIG.jpg
export DISPLAY=:0 && yad --title "Granice wytrzymałości film przygodowy Niemcy 2000 ^^^" \
   --on-top --sticky --center \
   --borders=5 \
   --timeout=1200 \
   --timeout-indicator=bottom \
   --image "/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/12-D923F9F0-154B-4964-9F6E-715CF5858D8A POLSAT_Film 18-20 GRANICE 1_PICTURE_BIG.jpg" \
   --button=gtk-quit\:1 &
exit 0
