#! /bin/bash
# Script generated by przyp.sh
#

p_IMG_FORUM=/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/13-B483402A-371E-456D-823A-69FCEAE9A9E2 Ale_kino+ 18-25 WAKACYJNA 8_PICTURE_FORUM.png
export DISPLAY=:0 && yad --title "Wakacyjna terapia komedia Francja 2018 ^^^" \
   --on-top --sticky --center \
   --borders=5 \
   --timeout=1200 \
   --timeout-indicator=bottom \
   --image "/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/13-B483402A-371E-456D-823A-69FCEAE9A9E2 Ale_kino+ 18-25 WAKACYJNA 8_PICTURE_FORUM.png" \
   --button=gtk-quit\:1 &
exit 0
