#! /bin/bash
# Script generated by przyp.sh
#

p_PIC=/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/14-1C947132-36E3-49E8-88CC-E415D6EBBF9C Planete_HD 18-30 POLSKA 1_PICTURE_BIG.jpg
export DISPLAY=:0 && yad --title "Polska z góry    Od małego Krakowa do małego Krakowa serial dokumentalny Polska " \
   --on-top --sticky --center \
   --borders=5 \
   --timeout=1200 \
   --timeout-indicator=bottom \
   --image "/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/14-1C947132-36E3-49E8-88CC-E415D6EBBF9C Planete_HD 18-30 POLSKA 1_PICTURE_BIG.jpg" \
   --button=gtk-quit\:1 &
exit 0
