#! /bin/bash
# Script generated by przyp.sh
#

paplay --volume=20000 "/home/rysio/Pobrane/PROGRAM_TV_ZEE/przypominajka.ogg" &
export DISPLAY=:0 && yad --title "Polska z góry    Od małego Krakowa do małego Krakowa serial dokumentalny Polska " \
   --on-top --sticky --center \
   --borders=5 \
   --timeout=1200 \
   --timeout-indicator=bottom \
   --image "/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/14-1C947132-36E3-49E8-88CC-E415D6EBBF9C Planete_HD 18-30 POLSKA 7_PICTURE_OUT.png" \
   --button="Otwórz obrazki"!gtk-ok\:"/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/14-1C947132-36E3-49E8-88CC-E415D6EBBF9C_PIC.sh" \
   --button="Otwórz forum"!gtk-ok\:"/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/14-1C947132-36E3-49E8-88CC-E415D6EBBF9C_FORUM.sh" \
   --button="Otwórz URL"!gtk-ok\:"/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/14-1C947132-36E3-49E8-88CC-E415D6EBBF9C_URL.sh" \
   --button=gtk-quit\:1 &
