#! /bin/bash
# Script generated by przyp.sh
#

paplay --volume=20000 "/home/rysio/Pobrane/PROGRAM_TV_ZEE/przypominajka.ogg" &
export DISPLAY=:0 && yad --title "Pojedynek na głosy komediodramat Wielka Brytania 2019 ^^^" \
   --on-top --sticky --center \
   --borders=5 \
   --timeout=1200 \
   --timeout-indicator=bottom \
   --image "/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/15-BC6A2068-1C1A-468B-93BC-6E5F3AB1EE24 Canal+ 18-40 POJEDYNEK 7_PICTURE_OUT.png" \
   --button="Otwórz obrazki"!gtk-ok\:"/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/15-BC6A2068-1C1A-468B-93BC-6E5F3AB1EE24_PIC.sh" \
   --button="Otwórz forum"!gtk-ok\:"/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/15-BC6A2068-1C1A-468B-93BC-6E5F3AB1EE24_FORUM.sh" \
   --button="Otwórz URL"!gtk-ok\:"/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/15-BC6A2068-1C1A-468B-93BC-6E5F3AB1EE24_URL.sh" \
   --button=gtk-quit\:1 &
