#! /bin/bash
# Script generated by przyp.sh
#

p_IMG_FORUM=/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/15-BC6A2068-1C1A-468B-93BC-6E5F3AB1EE24 Canal+ 18-40 POJEDYNEK 8_PICTURE_FORUM.png
export DISPLAY=:0 && yad --title "Pojedynek na głosy komediodramat Wielka Brytania 2019 ^^^" \
   --on-top --sticky --center \
   --borders=5 \
   --timeout=1200 \
   --timeout-indicator=bottom \
   --image "/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/15-BC6A2068-1C1A-468B-93BC-6E5F3AB1EE24 Canal+ 18-40 POJEDYNEK 8_PICTURE_FORUM.png" \
   --button=gtk-quit\:1 &
exit 0
