#! /bin/bash
# Script generated by przyp.sh
#

p_PIC=/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/16-9321A99E-3685-479E-867C-BC1BF1E85C56 TNT 18-42 KOCHA 1_PICTURE_BIG.jpg
export DISPLAY=:0 && yad --title "Kocha lubi szanuje komedia romantyczna ^^^" \
   --on-top --sticky --center \
   --borders=5 \
   --timeout=1200 \
   --timeout-indicator=bottom \
   --image "/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/16-9321A99E-3685-479E-867C-BC1BF1E85C56 TNT 18-42 KOCHA 1_PICTURE_BIG.jpg" \
   --button=gtk-quit\:1 &
exit 0
