#! /bin/bash
# Script generated by przyp.sh
#

p_IMG_FORUM=/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/17-2BDD23EA-0991-4188-B569-0CB17384AB85 BBC_Earth 18-55 JAK 8_PICTURE_FORUM.png
export DISPLAY=:0 && yad --title "Jak budowano imperia   serial dokumentalny Niemcy " \
   --on-top --sticky --center \
   --borders=5 \
   --timeout=1200 \
   --timeout-indicator=bottom \
   --image "/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/17-2BDD23EA-0991-4188-B569-0CB17384AB85 BBC_Earth 18-55 JAK 8_PICTURE_FORUM.png" \
   --button=gtk-quit\:1 &
exit 0
