#! /bin/bash
# Script generated by przyp.sh
#

p_PIC=/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/18-F58FA0F6-EE2A-48A4-BDF9-1717756DB821 CBS_Europa_HD 18-55 W 1_PICTURE_BIG.jpg
export DISPLAY=:0 && yad --title "W doborowym towarzystwie komediodramat USA 2004 ^^^" \
   --on-top --sticky --center \
   --borders=5 \
   --timeout=1200 \
   --timeout-indicator=bottom \
   --image "/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/18-F58FA0F6-EE2A-48A4-BDF9-1717756DB821 CBS_Europa_HD 18-55 W 1_PICTURE_BIG.jpg" \
   --button=gtk-quit\:1 &
exit 0
