#! /bin/bash
# Script generated by przyp.sh
#

paplay --volume=20000 "/home/rysio/Pobrane/PROGRAM_TV_ZEE/przypominajka.ogg" &
export DISPLAY=:0 && yad --title "Terminator Genisys film sensacyjny USA 2015 ^^" \
   --on-top --sticky --center \
   --borders=5 \
   --timeout=1200 \
   --timeout-indicator=bottom \
   --image "/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/19-C7C2B512-6714-45F8-9C04-03D956B4E0B2 HBO2 18-55 TERMINATOR 7_PICTURE_OUT.png" \
   --button="Otwórz obrazki"!gtk-ok\:"/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/19-C7C2B512-6714-45F8-9C04-03D956B4E0B2_PIC.sh" \
   --button="Otwórz forum"!gtk-ok\:"/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/19-C7C2B512-6714-45F8-9C04-03D956B4E0B2_FORUM.sh" \
   --button="Otwórz URL"!gtk-ok\:"/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/19-C7C2B512-6714-45F8-9C04-03D956B4E0B2_URL.sh" \
   --button=gtk-quit\:1 &
