#! /bin/bash
# Script generated by przyp.sh
#

p_PIC=/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/19-C7C2B512-6714-45F8-9C04-03D956B4E0B2 HBO2 18-55 TERMINATOR 1_PICTURE_BIG.jpg
export DISPLAY=:0 && yad --title "Terminator Genisys film sensacyjny USA 2015 ^^" \
   --on-top --sticky --center \
   --borders=5 \
   --timeout=1200 \
   --timeout-indicator=bottom \
   --image "/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/19-C7C2B512-6714-45F8-9C04-03D956B4E0B2 HBO2 18-55 TERMINATOR 1_PICTURE_BIG.jpg" \
   --button=gtk-quit\:1 &
exit 0
