#! /bin/bash
# Script generated by przyp.sh
#

p_IMG_FORUM=/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/20-276129B3-8551-454A-B18F-317D36E8ADB4 Planete_HD 19-00 MUSTANGI 8_PICTURE_FORUM.png
export DISPLAY=:0 && yad --title "Mustangi Dzikie konie Ameryki film dokumentalny Francja 2018" \
   --on-top --sticky --center \
   --borders=5 \
   --timeout=1200 \
   --timeout-indicator=bottom \
   --image "/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/20-276129B3-8551-454A-B18F-317D36E8ADB4 Planete_HD 19-00 MUSTANGI 8_PICTURE_FORUM.png" \
   --button=gtk-quit\:1 &
exit 0
