#! /bin/bash
# Script generated by przyp.sh
#

paplay --volume=20000 "/home/rysio/Pobrane/PROGRAM_TV_ZEE/przypominajka.ogg" &
export DISPLAY=:0 && yad --title "Mustangi Dzikie konie Ameryki film dokumentalny Francja 2018" \
   --on-top --sticky --center \
   --borders=5 \
   --timeout=1200 \
   --timeout-indicator=bottom \
   --image "/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/20-276129B3-8551-454A-B18F-317D36E8ADB4 Planete_HD 19-00 MUSTANGI 7_PICTURE_OUT.png" \
   --button="Otwórz obrazki"!gtk-ok\:"/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/20-276129B3-8551-454A-B18F-317D36E8ADB4_PIC.sh" \
   --button="Otwórz forum"!gtk-ok\:"/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/20-276129B3-8551-454A-B18F-317D36E8ADB4_FORUM.sh" \
   --button="Otwórz URL"!gtk-ok\:"/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/20-276129B3-8551-454A-B18F-317D36E8ADB4_URL.sh" \
   --button=gtk-quit\:1 &
