#! /bin/bash
# Script generated by przyp.sh
#

paplay --volume=20000 "/home/rysio/Pobrane/PROGRAM_TV_ZEE/przypominajka.ogg" &
export DISPLAY=:0 && yad --title "Ścigając wodne potwory    serial dokumentalny " \
   --on-top --sticky --center \
   --borders=5 \
   --timeout=1200 \
   --timeout-indicator=bottom \
   --image "/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/21-CD66F382-200E-43E6-A46E-28F73EDBCED3 BBC_Earth 19-55 ŚCIGAJĄC 7_PICTURE_OUT.png" \
   --button="Otwórz obrazki"!gtk-ok\:"/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/21-CD66F382-200E-43E6-A46E-28F73EDBCED3_PIC.sh" \
   --button="Otwórz forum"!gtk-ok\:"/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/21-CD66F382-200E-43E6-A46E-28F73EDBCED3_FORUM.sh" \
   --button="Otwórz URL"!gtk-ok\:"/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/21-CD66F382-200E-43E6-A46E-28F73EDBCED3_URL.sh" \
   --button=gtk-quit\:1 &
