#! /bin/bash
# Script generated by przyp.sh
#

p_PIC=/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/21-CD66F382-200E-43E6-A46E-28F73EDBCED3 BBC_Earth 19-55 ŚCIGAJĄC 1_PICTURE_BIG.jpg
export DISPLAY=:0 && yad --title "Ścigając wodne potwory    serial dokumentalny " \
   --on-top --sticky --center \
   --borders=5 \
   --timeout=1200 \
   --timeout-indicator=bottom \
   --image "/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/21-CD66F382-200E-43E6-A46E-28F73EDBCED3 BBC_Earth 19-55 ŚCIGAJĄC 1_PICTURE_BIG.jpg" \
   --button=gtk-quit\:1 &
exit 0
