#! /bin/bash
# Script generated by przyp.sh
#

p_PIC=/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/22-D2BCB53D-2A19-480E-BC1C-1B22A51759E0 C+_Film 20-00 ROK 1_PICTURE_BIG.jpg
export DISPLAY=:0 && yad --title "Rok na całe życie dramat obyczajowy USA 2020 ^^^" \
   --on-top --sticky --center \
   --borders=5 \
   --timeout=1200 \
   --timeout-indicator=bottom \
   --image "/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/22-D2BCB53D-2A19-480E-BC1C-1B22A51759E0 C+_Film 20-00 ROK 1_PICTURE_BIG.jpg" \
   --button=gtk-quit\:1 &
exit 0
