#! /bin/bash
# Script generated by przyp.sh
#

paplay --volume=20000 "/home/rysio/Pobrane/PROGRAM_TV_ZEE/przypominajka.ogg" &
export DISPLAY=:0 && yad --title "Rok na całe życie dramat obyczajowy USA 2020 ^^^" \
   --on-top --sticky --center \
   --borders=5 \
   --timeout=1200 \
   --timeout-indicator=bottom \
   --image "/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/22-D2BCB53D-2A19-480E-BC1C-1B22A51759E0 C+_Film 20-00 ROK 7_PICTURE_OUT.png" \
   --button="Otwórz obrazki"!gtk-ok\:"/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/22-D2BCB53D-2A19-480E-BC1C-1B22A51759E0_PIC.sh" \
   --button="Otwórz forum"!gtk-ok\:"/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/22-D2BCB53D-2A19-480E-BC1C-1B22A51759E0_FORUM.sh" \
   --button="Otwórz URL"!gtk-ok\:"/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/22-D2BCB53D-2A19-480E-BC1C-1B22A51759E0_URL.sh" \
   --button=gtk-quit\:1 &
