#! /bin/bash
# Script generated by przyp.sh
#

p_PIC=/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/23-762D2179-98B3-49BD-B3F8-9BA01009D638 Cinemax 20-00 SHINDISI 1_PICTURE_BIG.jpg
export DISPLAY=:0 && yad --title "Shindisi dramat obyczajowy Gruzja 2019 ^^^^" \
   --on-top --sticky --center \
   --borders=5 \
   --timeout=1200 \
   --timeout-indicator=bottom \
   --image "/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/23-762D2179-98B3-49BD-B3F8-9BA01009D638 Cinemax 20-00 SHINDISI 1_PICTURE_BIG.jpg" \
   --button=gtk-quit\:1 &
exit 0
