#! /bin/bash
# Script generated by przyp.sh
#

p_IMG_FORUM=/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/23-762D2179-98B3-49BD-B3F8-9BA01009D638 Cinemax 20-00 SHINDISI 8_PICTURE_FORUM.png
export DISPLAY=:0 && yad --title "Shindisi dramat obyczajowy Gruzja 2019 ^^^^" \
   --on-top --sticky --center \
   --borders=5 \
   --timeout=1200 \
   --timeout-indicator=bottom \
   --image "/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/23-762D2179-98B3-49BD-B3F8-9BA01009D638 Cinemax 20-00 SHINDISI 8_PICTURE_FORUM.png" \
   --button=gtk-quit\:1 &
exit 0
