#! /bin/bash
# Script generated by przyp.sh
#

p_PIC=/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/24-B032696F-448F-44F9-990A-F20A6A8D27D5 Kino_Polska 20-00 PAN 1_PICTURE_BIG.jpg
export DISPLAY=:0 && yad --title "Pan Wołodyjowski film historyczny Polska 1968 ^^^^" \
   --on-top --sticky --center \
   --borders=5 \
   --timeout=1200 \
   --timeout-indicator=bottom \
   --image "/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/24-B032696F-448F-44F9-990A-F20A6A8D27D5 Kino_Polska 20-00 PAN 1_PICTURE_BIG.jpg" \
   --button=gtk-quit\:1 &
exit 0
