#! /bin/bash
# Script generated by przyp.sh
#

p_PIC=/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/25-80A94917-B4D3-4FDA-AFB6-B85DEAE327ED Paramount_ChHD 20-00 STRAŻNIK 1_PICTURE_BIG.jpg
export DISPLAY=:0 && yad --title "Strażnik film sensacyjny USA 2006 ^^^" \
   --on-top --sticky --center \
   --borders=5 \
   --timeout=1200 \
   --timeout-indicator=bottom \
   --image "/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/25-80A94917-B4D3-4FDA-AFB6-B85DEAE327ED Paramount_ChHD 20-00 STRAŻNIK 1_PICTURE_BIG.jpg" \
   --button=gtk-quit\:1 &
exit 0
