#! /bin/bash
# Script generated by przyp.sh
#

p_IMG_FORUM=/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/26-00AFED43-439C-4581-A180-6482E08EC485 Planete_HD 20-00 OSTATNIA 8_PICTURE_FORUM.png
export DISPLAY=:0 && yad --title "Ostatnia żyrafa film dokumentalny Francja 2017" \
   --on-top --sticky --center \
   --borders=5 \
   --timeout=1200 \
   --timeout-indicator=bottom \
   --image "/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/26-00AFED43-439C-4581-A180-6482E08EC485 Planete_HD 20-00 OSTATNIA 8_PICTURE_FORUM.png" \
   --button=gtk-quit\:1 &
exit 0
