#! /bin/bash
# Script generated by przyp.sh
#

p_IMG_FORUM=/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/27-FB1F3E81-0900-4D26-8B28-5BC0D3291928 Stopklatka 20-00 PSYCHOL 8_PICTURE_FORUM.png
export DISPLAY=:0 && yad --title "Psychol thriller USA 1998 ^^^" \
   --on-top --sticky --center \
   --borders=5 \
   --timeout=1200 \
   --timeout-indicator=bottom \
   --image "/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/27-FB1F3E81-0900-4D26-8B28-5BC0D3291928 Stopklatka 20-00 PSYCHOL 8_PICTURE_FORUM.png" \
   --button=gtk-quit\:1 &
exit 0
