#! /bin/bash
# Script generated by przyp.sh
#

p_PIC=/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/28-10FAE458-DBB7-4F28-A5E1-1E40667497CE TVN_7 20-00 VOLTA 1_PICTURE_BIG.jpg
export DISPLAY=:0 && yad --title "Volta komedia Polska 2017 ^^" \
   --on-top --sticky --center \
   --borders=5 \
   --timeout=1200 \
   --timeout-indicator=bottom \
   --image "/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/28-10FAE458-DBB7-4F28-A5E1-1E40667497CE TVN_7 20-00 VOLTA 1_PICTURE_BIG.jpg" \
   --button=gtk-quit\:1 &
exit 0
