#! /bin/bash
# Script generated by przyp.sh
#

p_IMG_FORUM=/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/29-24CF591E-9E42-43D2-82C6-09DAD4321C54 TVN_Fabuła 20-00 R 8_PICTURE_FORUM.png
export DISPLAY=:0 && yad --title "R I P D Agenci z zaświatów komedia sensacyjna USA 2013 ^^" \
   --on-top --sticky --center \
   --borders=5 \
   --timeout=1200 \
   --timeout-indicator=bottom \
   --image "/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/29-24CF591E-9E42-43D2-82C6-09DAD4321C54 TVN_Fabuła 20-00 R 8_PICTURE_FORUM.png" \
   --button=gtk-quit\:1 &
exit 0
