#! /bin/bash
# Script generated by przyp.sh
#

p_IMG_FORUM=/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/30-300EC100-723F-4C7E-952F-3003FE6F4964 TVP_Kultura 20-00 ULICE 8_PICTURE_FORUM.png
export DISPLAY=:0 && yad --title "Ulice nędzy dramat kryminalny USA 1973 ^^^^" \
   --on-top --sticky --center \
   --borders=5 \
   --timeout=1200 \
   --timeout-indicator=bottom \
   --image "/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/30-300EC100-723F-4C7E-952F-3003FE6F4964 TVP_Kultura 20-00 ULICE 8_PICTURE_FORUM.png" \
   --button=gtk-quit\:1 &
exit 0
