#! /bin/bash
# Script generated by przyp.sh
#

p_IMG_FORUM=/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/31-68650762-569B-4F62-A12C-C4757DFC91D3 TV_Puls 20-00 AIR 8_PICTURE_FORUM.png
export DISPLAY=:0 && yad --title "Air Force One thriller Niemcy 1997 ^^^" \
   --on-top --sticky --center \
   --borders=5 \
   --timeout=1200 \
   --timeout-indicator=bottom \
   --image "/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/31-68650762-569B-4F62-A12C-C4757DFC91D3 TV_Puls 20-00 AIR 8_PICTURE_FORUM.png" \
   --button=gtk-quit\:1 &
exit 0
