#! /bin/bash
# Script generated by przyp.sh
#

p_IMG_FORUM=/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/32-28E60567-F3AD-4AAE-93A0-65DF14DE61CD POLSAT 20-05 TRANSFORMERS 8_PICTURE_FORUM.png
export DISPLAY=:0 && yad --title "Transformers Wiek zagłady film SF Chiny 2014 ^^^" \
   --on-top --sticky --center \
   --borders=5 \
   --timeout=1200 \
   --timeout-indicator=bottom \
   --image "/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/32-28E60567-F3AD-4AAE-93A0-65DF14DE61CD POLSAT 20-05 TRANSFORMERS 8_PICTURE_FORUM.png" \
   --button=gtk-quit\:1 &
exit 0
