#! /bin/bash
# Script generated by przyp.sh
#

paplay --volume=20000 "/home/rysio/Pobrane/PROGRAM_TV_ZEE/przypominajka.ogg" &
export DISPLAY=:0 && yad --title "Transformers Wiek zagłady film SF Chiny 2014 ^^^" \
   --on-top --sticky --center \
   --borders=5 \
   --timeout=1200 \
   --timeout-indicator=bottom \
   --image "/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/32-28E60567-F3AD-4AAE-93A0-65DF14DE61CD POLSAT 20-05 TRANSFORMERS 7_PICTURE_OUT.png" \
   --button="Otwórz obrazki"!gtk-ok\:"/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/32-28E60567-F3AD-4AAE-93A0-65DF14DE61CD_PIC.sh" \
   --button="Otwórz forum"!gtk-ok\:"/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/32-28E60567-F3AD-4AAE-93A0-65DF14DE61CD_FORUM.sh" \
   --button="Otwórz URL"!gtk-ok\:"/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/32-28E60567-F3AD-4AAE-93A0-65DF14DE61CD_URL.sh" \
   --button=gtk-quit\:1 &
