#! /bin/bash
# Script generated by przyp.sh
#

p_PIC=/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/33-7BFBA43C-BE56-478B-8940-E5A962491DBA Ale_kino+ 20-10 WIDOK 1_PICTURE_BIG.jpg
export DISPLAY=:0 && yad --title "Widok z sypialni thriller USA 1987 ^^^" \
   --on-top --sticky --center \
   --borders=5 \
   --timeout=1200 \
   --timeout-indicator=bottom \
   --image "/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/33-7BFBA43C-BE56-478B-8940-E5A962491DBA Ale_kino+ 20-10 WIDOK 1_PICTURE_BIG.jpg" \
   --button=gtk-quit\:1 &
exit 0
