#! /bin/bash
# Script generated by przyp.sh
#

p_IMG_FORUM=/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/34-9475483C-30A9-441A-B785-57A65B32CBDB Cinemax2 20-30 HUD 8_PICTURE_FORUM.png
export DISPLAY=:0 && yad --title "Hud syn farmera western USA 1963 ^^^^" \
   --on-top --sticky --center \
   --borders=5 \
   --timeout=1200 \
   --timeout-indicator=bottom \
   --image "/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/34-9475483C-30A9-441A-B785-57A65B32CBDB Cinemax2 20-30 HUD 8_PICTURE_FORUM.png" \
   --button=gtk-quit\:1 &
exit 0
