#! /bin/bash
# Script generated by przyp.sh
#

p_PIC=/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/35-0345BFDF-27B0-4D2F-8AF2-E97A44C39264 BBC_Earth 20-55 ŻYCIE 1_PICTURE_BIG.jpg
export DISPLAY=:0 && yad --title "Życie na pustkowiu    serial dokumentalny Wielka Brytania -" \
   --on-top --sticky --center \
   --borders=5 \
   --timeout=1200 \
   --timeout-indicator=bottom \
   --image "/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/35-0345BFDF-27B0-4D2F-8AF2-E97A44C39264 BBC_Earth 20-55 ŻYCIE 1_PICTURE_BIG.jpg" \
   --button=gtk-quit\:1 &
exit 0
