#! /bin/bash
# Script generated by przyp.sh
#

p_IMG_FORUM=/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/36-5347CAF8-EBD4-4DD3-9C8F-E5AD325B7B4B CBS_Europa_HD 21-00 BYŁO 8_PICTURE_FORUM.png
export DISPLAY=:0 && yad --title "Było sobie kłamstwo komedia USA 2009 ^^^" \
   --on-top --sticky --center \
   --borders=5 \
   --timeout=1200 \
   --timeout-indicator=bottom \
   --image "/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/36-5347CAF8-EBD4-4DD3-9C8F-E5AD325B7B4B CBS_Europa_HD 21-00 BYŁO 8_PICTURE_FORUM.png" \
   --button=gtk-quit\:1 &
exit 0
