#! /bin/bash
# Script generated by przyp.sh
#

p_PIC=/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/36-5347CAF8-EBD4-4DD3-9C8F-E5AD325B7B4B CBS_Europa_HD 21-00 BYŁO 1_PICTURE_BIG.jpg
export DISPLAY=:0 && yad --title "Było sobie kłamstwo komedia USA 2009 ^^^" \
   --on-top --sticky --center \
   --borders=5 \
   --timeout=1200 \
   --timeout-indicator=bottom \
   --image "/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/36-5347CAF8-EBD4-4DD3-9C8F-E5AD325B7B4B CBS_Europa_HD 21-00 BYŁO 1_PICTURE_BIG.jpg" \
   --button=gtk-quit\:1 &
exit 0
