#! /bin/bash
# Script generated by przyp.sh
#

paplay --volume=20000 "/home/rysio/Pobrane/PROGRAM_TV_ZEE/przypominajka.ogg" &
export DISPLAY=:0 && yad --title "Było sobie kłamstwo komedia USA 2009 ^^^" \
   --on-top --sticky --center \
   --borders=5 \
   --timeout=1200 \
   --timeout-indicator=bottom \
   --image "/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/36-5347CAF8-EBD4-4DD3-9C8F-E5AD325B7B4B CBS_Europa_HD 21-00 BYŁO 7_PICTURE_OUT.png" \
   --button="Otwórz obrazki"!gtk-ok\:"/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/36-5347CAF8-EBD4-4DD3-9C8F-E5AD325B7B4B_PIC.sh" \
   --button="Otwórz forum"!gtk-ok\:"/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/36-5347CAF8-EBD4-4DD3-9C8F-E5AD325B7B4B_FORUM.sh" \
   --button="Otwórz URL"!gtk-ok\:"/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/36-5347CAF8-EBD4-4DD3-9C8F-E5AD325B7B4B_URL.sh" \
   --button=gtk-quit\:1 &
