#! /bin/bash
# Script generated by przyp.sh
#

p_IMG_FORUM=/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/37-8AF7300B-FA63-4C0B-B136-9A993C0D9232 HBO2 21-00 PRAWDZIWE 8_PICTURE_FORUM.png
export DISPLAY=:0 && yad --title "Prawdziwe męstwo western USA 2010 ^^^^" \
   --on-top --sticky --center \
   --borders=5 \
   --timeout=1200 \
   --timeout-indicator=bottom \
   --image "/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/37-8AF7300B-FA63-4C0B-B136-9A993C0D9232 HBO2 21-00 PRAWDZIWE 8_PICTURE_FORUM.png" \
   --button=gtk-quit\:1 &
exit 0
