#! /bin/bash
# Script generated by przyp.sh
#

paplay --volume=20000 "/home/rysio/Pobrane/PROGRAM_TV_ZEE/przypominajka.ogg" &
export DISPLAY=:0 && yad --title "Zbudujmy to jeszcze raz    Wielki Mur Chiński serial dokumentalny Kanada " \
   --on-top --sticky --center \
   --borders=5 \
   --timeout=1200 \
   --timeout-indicator=bottom \
   --image "/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/39-51B0D8B5-4304-4B63-B7DA-6CCF0B631EB1 Planete_HD 21-00 ZBUDUJMY 7_PICTURE_OUT.png" \
   --button="Otwórz obrazki"!gtk-ok\:"/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/39-51B0D8B5-4304-4B63-B7DA-6CCF0B631EB1_PIC.sh" \
   --button="Otwórz forum"!gtk-ok\:"/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/39-51B0D8B5-4304-4B63-B7DA-6CCF0B631EB1_FORUM.sh" \
   --button="Otwórz URL"!gtk-ok\:"/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/39-51B0D8B5-4304-4B63-B7DA-6CCF0B631EB1_URL.sh" \
   --button=gtk-quit\:1 &
