#! /bin/bash
# Script generated by przyp.sh
#

p_IMG_FORUM=/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/40-C39C41DB-5DFA-4BD4-B2B9-C0D30C094F73 POLSAT_Film 21-00 LOT 8_PICTURE_FORUM.png
export DISPLAY=:0 && yad --title "Lot dramat obyczajowy USA 2012 ^^^^" \
   --on-top --sticky --center \
   --borders=5 \
   --timeout=1200 \
   --timeout-indicator=bottom \
   --image "/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/40-C39C41DB-5DFA-4BD4-B2B9-C0D30C094F73 POLSAT_Film 21-00 LOT 8_PICTURE_FORUM.png" \
   --button=gtk-quit\:1 &
exit 0
