#! /bin/bash
# Script generated by przyp.sh
#

paplay --volume=20000 "/home/rysio/Pobrane/PROGRAM_TV_ZEE/przypominajka.ogg" &
export DISPLAY=:0 && yad --title "Hamburger Hill dramat wojenny USA 1987 ^^" \
   --on-top --sticky --center \
   --borders=5 \
   --timeout=1200 \
   --timeout-indicator=bottom \
   --image "/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/41-A0297DCB-0F4C-4A05-81F3-D57C8C4D4ACA TNT 21-00 HAMBURGER 7_PICTURE_OUT.png" \
   --button="Otwórz obrazki"!gtk-ok\:"/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/41-A0297DCB-0F4C-4A05-81F3-D57C8C4D4ACA_PIC.sh" \
   --button="Otwórz forum"!gtk-ok\:"/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/41-A0297DCB-0F4C-4A05-81F3-D57C8C4D4ACA_FORUM.sh" \
   --button="Otwórz URL"!gtk-ok\:"/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/41-A0297DCB-0F4C-4A05-81F3-D57C8C4D4ACA_URL.sh" \
   --button=gtk-quit\:1 &
