#! /bin/bash
# Script generated by przyp.sh
#

p_PIC=/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/42-1439B5AB-34BC-4557-AC35-B934D156B07D HBO 21-35 PLAYER 1_PICTURE_BIG.jpg
export DISPLAY=:0 && yad --title "Player One film SF Indie 2018 ^^^^" \
   --on-top --sticky --center \
   --borders=5 \
   --timeout=1200 \
   --timeout-indicator=bottom \
   --image "/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/42-1439B5AB-34BC-4557-AC35-B934D156B07D HBO 21-35 PLAYER 1_PICTURE_BIG.jpg" \
   --button=gtk-quit\:1 &
exit 0
