#! /bin/bash
# Script generated by przyp.sh
#

p_PIC=/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/43-04DD1A93-1122-4A9C-BDE1-73A74E63F07B Cinemax 21-40 DO 1_PICTURE_BIG.jpg
export DISPLAY=:0 && yad --title "Do ostatniej śmierci horror animowany USA 2019 ^^^" \
   --on-top --sticky --center \
   --borders=5 \
   --timeout=1200 \
   --timeout-indicator=bottom \
   --image "/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/43-04DD1A93-1122-4A9C-BDE1-73A74E63F07B Cinemax 21-40 DO 1_PICTURE_BIG.jpg" \
   --button=gtk-quit\:1 &
exit 0
