#! /bin/bash
# Script generated by przyp.sh
#

paplay --volume=20000 "/home/rysio/Pobrane/PROGRAM_TV_ZEE/przypominajka.ogg" &
export DISPLAY=:0 && yad --title "Papierowe miasta dramat obyczajowy USA 2015 ^^^" \
   --on-top --sticky --center \
   --borders=5 \
   --timeout=1200 \
   --timeout-indicator=bottom \
   --image "/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/44-859A4774-6050-4730-8B3E-3BE0C4F020DC C+_Film 21-45 PAPIEROWE 7_PICTURE_OUT.png" \
   --button="Otwórz obrazki"!gtk-ok\:"/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/44-859A4774-6050-4730-8B3E-3BE0C4F020DC_PIC.sh" \
   --button="Otwórz forum"!gtk-ok\:"/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/44-859A4774-6050-4730-8B3E-3BE0C4F020DC_FORUM.sh" \
   --button="Otwórz URL"!gtk-ok\:"/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/44-859A4774-6050-4730-8B3E-3BE0C4F020DC_URL.sh" \
   --button=gtk-quit\:1 &
