#! /bin/bash
# Script generated by przyp.sh
#

p_IMG_FORUM=/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/44-859A4774-6050-4730-8B3E-3BE0C4F020DC C+_Film 21-45 PAPIEROWE 8_PICTURE_FORUM.png
export DISPLAY=:0 && yad --title "Papierowe miasta dramat obyczajowy USA 2015 ^^^" \
   --on-top --sticky --center \
   --borders=5 \
   --timeout=1200 \
   --timeout-indicator=bottom \
   --image "/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/44-859A4774-6050-4730-8B3E-3BE0C4F020DC C+_Film 21-45 PAPIEROWE 8_PICTURE_FORUM.png" \
   --button=gtk-quit\:1 &
exit 0
