#! /bin/bash
# Script generated by przyp.sh
#

p_PIC=/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/45-94B7B3B1-C102-4418-9EE6-32E2B8CE224F BBC_Earth 21-55 W 1_PICTURE_BIG.jpg
export DISPLAY=:0 && yad --title "W okowach mrozu    serial dokumentalny Wielka Brytania " \
   --on-top --sticky --center \
   --borders=5 \
   --timeout=1200 \
   --timeout-indicator=bottom \
   --image "/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/45-94B7B3B1-C102-4418-9EE6-32E2B8CE224F BBC_Earth 21-55 W 1_PICTURE_BIG.jpg" \
   --button=gtk-quit\:1 &
exit 0
