#! /bin/bash
# Script generated by przyp.sh
#

p_IMG_FORUM=/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/46-12BF3B3A-8B11-4003-B407-39085971194F FOX_ComedyHD 22-00 MASKA 8_PICTURE_FORUM.png
export DISPLAY=:0 && yad --title "Maska komedia USA 1994 ^^^^" \
   --on-top --sticky --center \
   --borders=5 \
   --timeout=1200 \
   --timeout-indicator=bottom \
   --image "/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/46-12BF3B3A-8B11-4003-B407-39085971194F FOX_ComedyHD 22-00 MASKA 8_PICTURE_FORUM.png" \
   --button=gtk-quit\:1 &
exit 0
