#! /bin/bash
# Script generated by przyp.sh
#

p_IMG_FORUM=/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/47-A9D3F7EF-F065-416E-ADA7-6CA1A6E1883E Planete_HD 22-00 ZBUDUJMY 8_PICTURE_FORUM.png
export DISPLAY=:0 && yad --title "Zbudujmy to jeszcze raz    Wenecja serial dokumentalny Kanada " \
   --on-top --sticky --center \
   --borders=5 \
   --timeout=1200 \
   --timeout-indicator=bottom \
   --image "/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/47-A9D3F7EF-F065-416E-ADA7-6CA1A6E1883E Planete_HD 22-00 ZBUDUJMY 8_PICTURE_FORUM.png" \
   --button=gtk-quit\:1 &
exit 0
