#! /bin/bash
# Script generated by przyp.sh
#

p_IMG_FORUM=/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/48-902134C8-3D39-4A53-9A68-E1178968D6B8 TVN_Fabuła 22-00 PRAWDZIWA 8_PICTURE_FORUM.png
export DISPLAY=:0 && yad --title "Prawdziwa zbrodnia thriller USA 1999 ^^^" \
   --on-top --sticky --center \
   --borders=5 \
   --timeout=1200 \
   --timeout-indicator=bottom \
   --image "/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/48-902134C8-3D39-4A53-9A68-E1178968D6B8 TVN_Fabuła 22-00 PRAWDZIWA 8_PICTURE_FORUM.png" \
   --button=gtk-quit\:1 &
exit 0
