#! /bin/bash
# Script generated by przyp.sh
#

paplay --volume=20000 "/home/rysio/Pobrane/PROGRAM_TV_ZEE/przypominajka.ogg" &
export DISPLAY=:0 && yad --title "Prawdziwa zbrodnia thriller USA 1999 ^^^" \
   --on-top --sticky --center \
   --borders=5 \
   --timeout=1200 \
   --timeout-indicator=bottom \
   --image "/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/48-902134C8-3D39-4A53-9A68-E1178968D6B8 TVN_Fabuła 22-00 PRAWDZIWA 7_PICTURE_OUT.png" \
   --button="Otwórz obrazki"!gtk-ok\:"/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/48-902134C8-3D39-4A53-9A68-E1178968D6B8_PIC.sh" \
   --button="Otwórz forum"!gtk-ok\:"/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/48-902134C8-3D39-4A53-9A68-E1178968D6B8_FORUM.sh" \
   --button="Otwórz URL"!gtk-ok\:"/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/48-902134C8-3D39-4A53-9A68-E1178968D6B8_URL.sh" \
   --button=gtk-quit\:1 &
