#! /bin/bash
# Script generated by przyp.sh
#

paplay --volume=20000 "/home/rysio/Pobrane/PROGRAM_TV_ZEE/przypominajka.ogg" &
export DISPLAY=:0 && yad --title "Autostopowicz thriller USA 2007 ^^^" \
   --on-top --sticky --center \
   --borders=5 \
   --timeout=1200 \
   --timeout-indicator=bottom \
   --image "/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/49-D85A4493-B357-4CA8-B9ED-E2DE562D25BB Stopklatka 22-10 AUTOSTOPOWICZ 7_PICTURE_OUT.png" \
   --button="Otwórz obrazki"!gtk-ok\:"/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/49-D85A4493-B357-4CA8-B9ED-E2DE562D25BB_PIC.sh" \
   --button="Otwórz forum"!gtk-ok\:"/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/49-D85A4493-B357-4CA8-B9ED-E2DE562D25BB_FORUM.sh" \
   --button="Otwórz URL"!gtk-ok\:"/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/49-D85A4493-B357-4CA8-B9ED-E2DE562D25BB_URL.sh" \
   --button=gtk-quit\:1 &
