#! /bin/bash
# Script generated by przyp.sh
#

p_IMG_FORUM=/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/49-D85A4493-B357-4CA8-B9ED-E2DE562D25BB Stopklatka 22-10 AUTOSTOPOWICZ 8_PICTURE_FORUM.png
export DISPLAY=:0 && yad --title "Autostopowicz thriller USA 2007 ^^^" \
   --on-top --sticky --center \
   --borders=5 \
   --timeout=1200 \
   --timeout-indicator=bottom \
   --image "/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/49-D85A4493-B357-4CA8-B9ED-E2DE562D25BB Stopklatka 22-10 AUTOSTOPOWICZ 8_PICTURE_FORUM.png" \
   --button=gtk-quit\:1 &
exit 0
