#! /bin/bash
# Script generated by przyp.sh
#

paplay --volume=20000 "/home/rysio/Pobrane/PROGRAM_TV_ZEE/przypominajka.ogg" &
export DISPLAY=:0 && yad --title "Wizyta horror USA 2015 ^^^" \
   --on-top --sticky --center \
   --borders=5 \
   --timeout=1200 \
   --timeout-indicator=bottom \
   --image "/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/50-F93ABBE4-A2CD-4AF6-8653-B5347EF92F83 TVN_7 22-15 WIZYTA 7_PICTURE_OUT.png" \
   --button="Otwórz obrazki"!gtk-ok\:"/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/50-F93ABBE4-A2CD-4AF6-8653-B5347EF92F83_PIC.sh" \
   --button="Otwórz forum"!gtk-ok\:"/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/50-F93ABBE4-A2CD-4AF6-8653-B5347EF92F83_FORUM.sh" \
   --button="Otwórz URL"!gtk-ok\:"/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/50-F93ABBE4-A2CD-4AF6-8653-B5347EF92F83_URL.sh" \
   --button=gtk-quit\:1 &
