#! /bin/bash
# Script generated by przyp.sh
#

p_PIC=/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/50-F93ABBE4-A2CD-4AF6-8653-B5347EF92F83 TVN_7 22-15 WIZYTA 1_PICTURE_BIG.jpg
export DISPLAY=:0 && yad --title "Wizyta horror USA 2015 ^^^" \
   --on-top --sticky --center \
   --borders=5 \
   --timeout=1200 \
   --timeout-indicator=bottom \
   --image "/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/50-F93ABBE4-A2CD-4AF6-8653-B5347EF92F83 TVN_7 22-15 WIZYTA 1_PICTURE_BIG.jpg" \
   --button=gtk-quit\:1 &
exit 0
