#! /bin/bash
# Script generated by przyp.sh
#

p_IMG_FORUM=/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/51-85FECA43-C8B5-47ED-A657-24FA463591AA Paramount_ChHD 22-20 WŁOSKA 8_PICTURE_FORUM.png
export DISPLAY=:0 && yad --title "Włoska robota film sensacyjny Wielka Brytania 2003 ^^^" \
   --on-top --sticky --center \
   --borders=5 \
   --timeout=1200 \
   --timeout-indicator=bottom \
   --image "/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/51-85FECA43-C8B5-47ED-A657-24FA463591AA Paramount_ChHD 22-20 WŁOSKA 8_PICTURE_FORUM.png" \
   --button=gtk-quit\:1 &
exit 0
