#! /bin/bash
# Script generated by przyp.sh
#

paplay --volume=20000 "/home/rysio/Pobrane/PROGRAM_TV_ZEE/przypominajka.ogg" &
export DISPLAY=:0 && yad --title "Włoska robota film sensacyjny Wielka Brytania 2003 ^^^" \
   --on-top --sticky --center \
   --borders=5 \
   --timeout=1200 \
   --timeout-indicator=bottom \
   --image "/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/51-85FECA43-C8B5-47ED-A657-24FA463591AA Paramount_ChHD 22-20 WŁOSKA 7_PICTURE_OUT.png" \
   --button="Otwórz obrazki"!gtk-ok\:"/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/51-85FECA43-C8B5-47ED-A657-24FA463591AA_PIC.sh" \
   --button="Otwórz forum"!gtk-ok\:"/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/51-85FECA43-C8B5-47ED-A657-24FA463591AA_FORUM.sh" \
   --button="Otwórz URL"!gtk-ok\:"/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/51-85FECA43-C8B5-47ED-A657-24FA463591AA_URL.sh" \
   --button=gtk-quit\:1 &
