#! /bin/bash
# Script generated by przyp.sh
#

paplay --volume=20000 "/home/rysio/Pobrane/PROGRAM_TV_ZEE/przypominajka.ogg" &
export DISPLAY=:0 && yad --title "Serce świata dramat obyczajowy Brazylia 2019 ^^^^" \
   --on-top --sticky --center \
   --borders=5 \
   --timeout=1200 \
   --timeout-indicator=bottom \
   --image "/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/52-0BCC6C9A-1C3D-44CF-A077-E1340867F88A Cinemax2 22-25 SERCE 7_PICTURE_OUT.png" \
   --button="Otwórz obrazki"!gtk-ok\:"/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/52-0BCC6C9A-1C3D-44CF-A077-E1340867F88A_PIC.sh" \
   --button="Otwórz forum"!gtk-ok\:"/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/52-0BCC6C9A-1C3D-44CF-A077-E1340867F88A_FORUM.sh" \
   --button="Otwórz URL"!gtk-ok\:"/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/52-0BCC6C9A-1C3D-44CF-A077-E1340867F88A_URL.sh" \
   --button=gtk-quit\:1 &
