#! /bin/bash
# Script generated by przyp.sh
#

p_PIC=/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/52-0BCC6C9A-1C3D-44CF-A077-E1340867F88A Cinemax2 22-25 SERCE 1_PICTURE_BIG.jpg
export DISPLAY=:0 && yad --title "Serce świata dramat obyczajowy Brazylia 2019 ^^^^" \
   --on-top --sticky --center \
   --borders=5 \
   --timeout=1200 \
   --timeout-indicator=bottom \
   --image "/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/52-0BCC6C9A-1C3D-44CF-A077-E1340867F88A Cinemax2 22-25 SERCE 1_PICTURE_BIG.jpg" \
   --button=gtk-quit\:1 &
exit 0
