#! /bin/bash
# Script generated by przyp.sh
#

paplay --volume=20000 "/home/rysio/Pobrane/PROGRAM_TV_ZEE/przypominajka.ogg" &
export DISPLAY=:0 && yad --title "Dziedzictwo krwi film sensacyjny Francja 2016 ^^^" \
   --on-top --sticky --center \
   --borders=5 \
   --timeout=1200 \
   --timeout-indicator=bottom \
   --image "/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/53-809D09E1-72C5-4627-907D-69D60AFD29BB TV_Puls 22-35 DZIEDZICTWO 7_PICTURE_OUT.png" \
   --button="Otwórz obrazki"!gtk-ok\:"/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/53-809D09E1-72C5-4627-907D-69D60AFD29BB_PIC.sh" \
   --button="Otwórz forum"!gtk-ok\:"/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/53-809D09E1-72C5-4627-907D-69D60AFD29BB_FORUM.sh" \
   --button="Otwórz URL"!gtk-ok\:"/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/53-809D09E1-72C5-4627-907D-69D60AFD29BB_URL.sh" \
   --button=gtk-quit\:1 &
