#! /bin/bash
# Script generated by przyp.sh
#

p_PIC=/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/53-809D09E1-72C5-4627-907D-69D60AFD29BB TV_Puls 22-35 DZIEDZICTWO 1_PICTURE_BIG.jpg
export DISPLAY=:0 && yad --title "Dziedzictwo krwi film sensacyjny Francja 2016 ^^^" \
   --on-top --sticky --center \
   --borders=5 \
   --timeout=1200 \
   --timeout-indicator=bottom \
   --image "/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/53-809D09E1-72C5-4627-907D-69D60AFD29BB TV_Puls 22-35 DZIEDZICTWO 1_PICTURE_BIG.jpg" \
   --button=gtk-quit\:1 &
exit 0
