#! /bin/bash
# Script generated by przyp.sh
#

p_IMG_FORUM=/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/54-4F19FF6B-5FC7-455A-9302-FB23B81A84B3 CBS_Europa_HD 22-55 HALLOWEEN 8_PICTURE_FORUM.png
export DISPLAY=:0 && yad --title "Halloween 2 horror USA 1981 ^^" \
   --on-top --sticky --center \
   --borders=5 \
   --timeout=1200 \
   --timeout-indicator=bottom \
   --image "/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/54-4F19FF6B-5FC7-455A-9302-FB23B81A84B3 CBS_Europa_HD 22-55 HALLOWEEN 8_PICTURE_FORUM.png" \
   --button=gtk-quit\:1 &
exit 0
