#! /bin/bash
# Script generated by przyp.sh
#

p_IMG_FORUM=/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/55-D100625E-AC38-4474-B969-E6F5C357494B BBC_Earth 23-00 PODRÓŻE 8_PICTURE_FORUM.png
export DISPLAY=:0 && yad --title "Podróże Michaela Palina   serial dokumentalny Wielka Brytania " \
   --on-top --sticky --center \
   --borders=5 \
   --timeout=1200 \
   --timeout-indicator=bottom \
   --image "/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/55-D100625E-AC38-4474-B969-E6F5C357494B BBC_Earth 23-00 PODRÓŻE 8_PICTURE_FORUM.png" \
   --button=gtk-quit\:1 &
exit 0
