#! /bin/bash
# Script generated by przyp.sh
#

p_PIC=/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/56-B37E6D6E-8795-47EC-910F-64C0A908E3A4 Canal+ 23-00 25 1_PICTURE_BIG.jpg
export DISPLAY=:0 && yad --title "25 lat niewinności Sprawa Tomka Komendy dramat biograficzny Polska 2020 ^^^^" \
   --on-top --sticky --center \
   --borders=5 \
   --timeout=1200 \
   --timeout-indicator=bottom \
   --image "/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/56-B37E6D6E-8795-47EC-910F-64C0A908E3A4 Canal+ 23-00 25 1_PICTURE_BIG.jpg" \
   --button=gtk-quit\:1 &
exit 0
