#! /bin/bash
# Script generated by przyp.sh
#

paplay --volume=20000 "/home/rysio/Pobrane/PROGRAM_TV_ZEE/przypominajka.ogg" &
export DISPLAY=:0 && yad --title "Assassin's Creed film przygodowy Malta 2016 ^^" \
   --on-top --sticky --center \
   --borders=5 \
   --timeout=1200 \
   --timeout-indicator=bottom \
   --image "/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/57-A20A4DFE-B290-4FD0-84E2-9D237EAB67A8 FOX_HD 23-00 ASSASSIN'S 7_PICTURE_OUT.png" \
   --button="Otwórz obrazki"!gtk-ok\:"/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/57-A20A4DFE-B290-4FD0-84E2-9D237EAB67A8_PIC.sh" \
   --button="Otwórz forum"!gtk-ok\:"/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/57-A20A4DFE-B290-4FD0-84E2-9D237EAB67A8_FORUM.sh" \
   --button="Otwórz URL"!gtk-ok\:"/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/57-A20A4DFE-B290-4FD0-84E2-9D237EAB67A8_URL.sh" \
   --button=gtk-quit\:1 &
