#! /bin/bash
# Script generated by przyp.sh
#

p_IMG_FORUM=/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/57-A20A4DFE-B290-4FD0-84E2-9D237EAB67A8 FOX_HD 23-00 ASSASSIN'S 8_PICTURE_FORUM.png
export DISPLAY=:0 && yad --title "Assassin's Creed film przygodowy Malta 2016 ^^" \
   --on-top --sticky --center \
   --borders=5 \
   --timeout=1200 \
   --timeout-indicator=bottom \
   --image "/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/57-A20A4DFE-B290-4FD0-84E2-9D237EAB67A8 FOX_HD 23-00 ASSASSIN'S 8_PICTURE_FORUM.png" \
   --button=gtk-quit\:1 &
exit 0
