#! /bin/bash
# Script generated by przyp.sh
#

p_IMG_FORUM=/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/58-36CE265F-7993-4950-8409-FC291A9AAB0A Kino_TV_HD 23-00 UNIWERSALNY 8_PICTURE_FORUM.png
export DISPLAY=:0 && yad --title "Uniwersalny żołnierz Dzień odrodzenia thriller SF USA 2012 ^^^" \
   --on-top --sticky --center \
   --borders=5 \
   --timeout=1200 \
   --timeout-indicator=bottom \
   --image "/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/58-36CE265F-7993-4950-8409-FC291A9AAB0A Kino_TV_HD 23-00 UNIWERSALNY 8_PICTURE_FORUM.png" \
   --button=gtk-quit\:1 &
exit 0
