#! /bin/bash
# Script generated by przyp.sh
#

paplay --volume=20000 "/home/rysio/Pobrane/PROGRAM_TV_ZEE/przypominajka.ogg" &
export DISPLAY=:0 && yad --title "Uniwersalny żołnierz Dzień odrodzenia thriller SF USA 2012 ^^^" \
   --on-top --sticky --center \
   --borders=5 \
   --timeout=1200 \
   --timeout-indicator=bottom \
   --image "/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/58-36CE265F-7993-4950-8409-FC291A9AAB0A Kino_TV_HD 23-00 UNIWERSALNY 7_PICTURE_OUT.png" \
   --button="Otwórz obrazki"!gtk-ok\:"/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/58-36CE265F-7993-4950-8409-FC291A9AAB0A_PIC.sh" \
   --button="Otwórz forum"!gtk-ok\:"/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/58-36CE265F-7993-4950-8409-FC291A9AAB0A_FORUM.sh" \
   --button="Otwórz URL"!gtk-ok\:"/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/58-36CE265F-7993-4950-8409-FC291A9AAB0A_URL.sh" \
   --button=gtk-quit\:1 &
