#! /bin/bash
# Script generated by przyp.sh
#

p_PIC=/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/59-AF848661-D68B-4194-B601-C5F67AACCDE7 Planete_HD 23-00 MONT 1_PICTURE_BIG.jpg
export DISPLAY=:0 && yad --title "Mont Saint-Michel sanktuarium na wyspie film dokumentalny Francja 2017" \
   --on-top --sticky --center \
   --borders=5 \
   --timeout=1200 \
   --timeout-indicator=bottom \
   --image "/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/59-AF848661-D68B-4194-B601-C5F67AACCDE7 Planete_HD 23-00 MONT 1_PICTURE_BIG.jpg" \
   --button=gtk-quit\:1 &
exit 0
