#! /bin/bash
# Script generated by przyp.sh
#

p_IMG_FORUM=/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/60-B8EA3C4C-DFEE-46F5-876F-30237AAF3CE8 HBO3 23-10 TO 8_PICTURE_FORUM.png
export DISPLAY=:0 && yad --title "To Rozdział 2 horror USA 2019 ^^^" \
   --on-top --sticky --center \
   --borders=5 \
   --timeout=1200 \
   --timeout-indicator=bottom \
   --image "/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/60-B8EA3C4C-DFEE-46F5-876F-30237AAF3CE8 HBO3 23-10 TO 8_PICTURE_FORUM.png" \
   --button=gtk-quit\:1 &
exit 0
