#! /bin/bash
# Script generated by przyp.sh
#

paplay --volume=20000 "/home/rysio/Pobrane/PROGRAM_TV_ZEE/przypominajka.ogg" &
export DISPLAY=:0 && yad --title "To Rozdział 2 horror USA 2019 ^^^" \
   --on-top --sticky --center \
   --borders=5 \
   --timeout=1200 \
   --timeout-indicator=bottom \
   --image "/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/60-B8EA3C4C-DFEE-46F5-876F-30237AAF3CE8 HBO3 23-10 TO 7_PICTURE_OUT.png" \
   --button="Otwórz obrazki"!gtk-ok\:"/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/60-B8EA3C4C-DFEE-46F5-876F-30237AAF3CE8_PIC.sh" \
   --button="Otwórz forum"!gtk-ok\:"/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/60-B8EA3C4C-DFEE-46F5-876F-30237AAF3CE8_FORUM.sh" \
   --button="Otwórz URL"!gtk-ok\:"/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/60-B8EA3C4C-DFEE-46F5-876F-30237AAF3CE8_URL.sh" \
   --button=gtk-quit\:1 &
