#! /bin/bash
# Script generated by przyp.sh
#

paplay --volume=20000 "/home/rysio/Pobrane/PROGRAM_TV_ZEE/przypominajka.ogg" &
export DISPLAY=:0 && yad --title "PitBull film kryminalny Polska 2005 ^^^^" \
   --on-top --sticky --center \
   --borders=5 \
   --timeout=1200 \
   --timeout-indicator=bottom \
   --image "/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/61-E65D513D-DBEA-4B3C-9829-C9CA479C6F04 Kino_Polska 23-10 PITBULL 7_PICTURE_OUT.png" \
   --button="Otwórz obrazki"!gtk-ok\:"/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/61-E65D513D-DBEA-4B3C-9829-C9CA479C6F04_PIC.sh" \
   --button="Otwórz forum"!gtk-ok\:"/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/61-E65D513D-DBEA-4B3C-9829-C9CA479C6F04_FORUM.sh" \
   --button="Otwórz URL"!gtk-ok\:"/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/61-E65D513D-DBEA-4B3C-9829-C9CA479C6F04_URL.sh" \
   --button=gtk-quit\:1 &
