#! /bin/bash
# Script generated by przyp.sh
#

p_IMG_FORUM=/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/61-E65D513D-DBEA-4B3C-9829-C9CA479C6F04 Kino_Polska 23-10 PITBULL 8_PICTURE_FORUM.png
export DISPLAY=:0 && yad --title "PitBull film kryminalny Polska 2005 ^^^^" \
   --on-top --sticky --center \
   --borders=5 \
   --timeout=1200 \
   --timeout-indicator=bottom \
   --image "/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/61-E65D513D-DBEA-4B3C-9829-C9CA479C6F04 Kino_Polska 23-10 PITBULL 8_PICTURE_FORUM.png" \
   --button=gtk-quit\:1 &
exit 0
