#! /bin/bash
# Script generated by przyp.sh
#

p_PIC=/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/62-50119940-B957-43BD-A802-D6AF20FB26ED TNT 23-10 ZABÓJCA 1_PICTURE_BIG.jpg
export DISPLAY=:0 && yad --title "Zabójca thriller Kanada 1991 ^^^" \
   --on-top --sticky --center \
   --borders=5 \
   --timeout=1200 \
   --timeout-indicator=bottom \
   --image "/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/62-50119940-B957-43BD-A802-D6AF20FB26ED TNT 23-10 ZABÓJCA 1_PICTURE_BIG.jpg" \
   --button=gtk-quit\:1 &
exit 0
