#! /bin/bash
# Script generated by przyp.sh
#

p_IMG_FORUM=/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/63-73E95591-C436-4C7B-948A-C456CE47F368 Cinemax 23-15 DRAMAT 8_PICTURE_FORUM.png
export DISPLAY=:0 && yad --title "Dramat komediodramat Korea Południowa 2019 ^^^" \
   --on-top --sticky --center \
   --borders=5 \
   --timeout=1200 \
   --timeout-indicator=bottom \
   --image "/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/63-73E95591-C436-4C7B-948A-C456CE47F368 Cinemax 23-15 DRAMAT 8_PICTURE_FORUM.png" \
   --button=gtk-quit\:1 &
exit 0
