#! /bin/bash
# Script generated by przyp.sh
#

paplay --volume=20000 "/home/rysio/Pobrane/PROGRAM_TV_ZEE/przypominajka.ogg" &
export DISPLAY=:0 && yad --title "Serce do walki dramat obyczajowy Polska 2019 ^^^" \
   --on-top --sticky --center \
   --borders=5 \
   --timeout=1200 \
   --timeout-indicator=bottom \
   --image "/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/64-D2626C7C-B05B-4978-A6AF-E6947AB1F4C8 C+_Film 23-30 SERCE 7_PICTURE_OUT.png" \
   --button="Otwórz obrazki"!gtk-ok\:"/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/64-D2626C7C-B05B-4978-A6AF-E6947AB1F4C8_PIC.sh" \
   --button="Otwórz forum"!gtk-ok\:"/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/64-D2626C7C-B05B-4978-A6AF-E6947AB1F4C8_FORUM.sh" \
   --button="Otwórz URL"!gtk-ok\:"/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/64-D2626C7C-B05B-4978-A6AF-E6947AB1F4C8_URL.sh" \
   --button=gtk-quit\:1 &
