#! /bin/bash
# Script generated by przyp.sh
#

p_IMG_FORUM=/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/64-D2626C7C-B05B-4978-A6AF-E6947AB1F4C8 C+_Film 23-30 SERCE 8_PICTURE_FORUM.png
export DISPLAY=:0 && yad --title "Serce do walki dramat obyczajowy Polska 2019 ^^^" \
   --on-top --sticky --center \
   --borders=5 \
   --timeout=1200 \
   --timeout-indicator=bottom \
   --image "/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/64-D2626C7C-B05B-4978-A6AF-E6947AB1F4C8 C+_Film 23-30 SERCE 8_PICTURE_FORUM.png" \
   --button=gtk-quit\:1 &
exit 0
