#! /bin/bash
# Script generated by przyp.sh
#

p_IMG_FORUM=/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/66-1D0F2B1F-6FAB-47B5-B73D-A9829F7165C0 POLSAT 23-40 MISSION 8_PICTURE_FORUM.png
export DISPLAY=:0 && yad --title "Mission Impossible film sensacyjny USA 1996 ^^^^" \
   --on-top --sticky --center \
   --borders=5 \
   --timeout=1200 \
   --timeout-indicator=bottom \
   --image "/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/66-1D0F2B1F-6FAB-47B5-B73D-A9829F7165C0 POLSAT 23-40 MISSION 8_PICTURE_FORUM.png" \
   --button=gtk-quit\:1 &
exit 0
