#! /bin/bash
# Script generated by przyp.sh
#

paplay --volume=20000 "/home/rysio/Pobrane/PROGRAM_TV_ZEE/przypominajka.ogg" &
export DISPLAY=:0 && yad --title "Nocne życie komedia romantyczna Niemcy 2020 ^^^" \
   --on-top --sticky --center \
   --borders=5 \
   --timeout=1200 \
   --timeout-indicator=bottom \
   --image "/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/67-FEF8E8CA-8A2B-48F0-8473-CE67B07FED3C HBO2 23-45 NOCNE 7_PICTURE_OUT.png" \
   --button="Otwórz obrazki"!gtk-ok\:"/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/67-FEF8E8CA-8A2B-48F0-8473-CE67B07FED3C_PIC.sh" \
   --button="Otwórz forum"!gtk-ok\:"/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/67-FEF8E8CA-8A2B-48F0-8473-CE67B07FED3C_FORUM.sh" \
   --button="Otwórz URL"!gtk-ok\:"/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/67-FEF8E8CA-8A2B-48F0-8473-CE67B07FED3C_URL.sh" \
   --button=gtk-quit\:1 &
