#! /bin/bash
# Script generated by przyp.sh
#

p_IMG_FORUM=/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/67-FEF8E8CA-8A2B-48F0-8473-CE67B07FED3C HBO2 23-45 NOCNE 8_PICTURE_FORUM.png
export DISPLAY=:0 && yad --title "Nocne życie komedia romantyczna Niemcy 2020 ^^^" \
   --on-top --sticky --center \
   --borders=5 \
   --timeout=1200 \
   --timeout-indicator=bottom \
   --image "/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/67-FEF8E8CA-8A2B-48F0-8473-CE67B07FED3C HBO2 23-45 NOCNE 8_PICTURE_FORUM.png" \
   --button=gtk-quit\:1 &
exit 0
