#! /bin/bash
# Script generated by przyp.sh
#

p_PIC=/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/68-0CD1DE9A-8396-41FA-AB95-C83873767F87 HBO 23-50 EQUILIBRIUM 1_PICTURE_BIG.jpg
export DISPLAY=:0 && yad --title "Equilibrium film SF USA 2002 ^^^" \
   --on-top --sticky --center \
   --borders=5 \
   --timeout=1200 \
   --timeout-indicator=bottom \
   --image "/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/68-0CD1DE9A-8396-41FA-AB95-C83873767F87 HBO 23-50 EQUILIBRIUM 1_PICTURE_BIG.jpg" \
   --button=gtk-quit\:1 &
exit 0
