#! /bin/bash
# Script generated by przyp.sh
#

p_IMG_FORUM=/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/69-C79F9413-FEE6-48E9-9F1D-F12901DC01AD TVP_1 23-50 JACK 8_PICTURE_FORUM.png
export DISPLAY=:0 && yad --title "Jack Hunter w poszukiwaniu grobowca Echnatona film przygodowy USA 2008 ^^" \
   --on-top --sticky --center \
   --borders=5 \
   --timeout=1200 \
   --timeout-indicator=bottom \
   --image "/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/69-C79F9413-FEE6-48E9-9F1D-F12901DC01AD TVP_1 23-50 JACK 8_PICTURE_FORUM.png" \
   --button=gtk-quit\:1 &
exit 0
