#! /bin/bash
# Script generated by przyp.sh
#

paplay --volume=20000 "/home/rysio/Pobrane/PROGRAM_TV_ZEE/przypominajka.ogg" &
export DISPLAY=:0 && yad --title "Jack Hunter w poszukiwaniu grobowca Echnatona film przygodowy USA 2008 ^^" \
   --on-top --sticky --center \
   --borders=5 \
   --timeout=1200 \
   --timeout-indicator=bottom \
   --image "/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/69-C79F9413-FEE6-48E9-9F1D-F12901DC01AD TVP_1 23-50 JACK 7_PICTURE_OUT.png" \
   --button="Otwórz obrazki"!gtk-ok\:"/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/69-C79F9413-FEE6-48E9-9F1D-F12901DC01AD_PIC.sh" \
   --button="Otwórz forum"!gtk-ok\:"/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/69-C79F9413-FEE6-48E9-9F1D-F12901DC01AD_FORUM.sh" \
   --button="Otwórz URL"!gtk-ok\:"/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/69-C79F9413-FEE6-48E9-9F1D-F12901DC01AD_URL.sh" \
   --button=gtk-quit\:1 &
