#! /bin/bash
# Script generated by przyp.sh
#

paplay --volume=20000 "/home/rysio/Pobrane/PROGRAM_TV_ZEE/przypominajka.ogg" &
export DISPLAY=:0 && yad --title "Następne 48 godzin komedia sensacyjna USA 1990 ^^^" \
   --on-top --sticky --center \
   --borders=5 \
   --timeout=1200 \
   --timeout-indicator=bottom \
   --image "/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/71-BB6A0C0B-4018-4C94-AA64-BC1501459D60 POLSAT_Film 23-55 NASTĘPNE 7_PICTURE_OUT.png" \
   --button="Otwórz obrazki"!gtk-ok\:"/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/71-BB6A0C0B-4018-4C94-AA64-BC1501459D60_PIC.sh" \
   --button="Otwórz forum"!gtk-ok\:"/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/71-BB6A0C0B-4018-4C94-AA64-BC1501459D60_FORUM.sh" \
   --button="Otwórz URL"!gtk-ok\:"/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/71-BB6A0C0B-4018-4C94-AA64-BC1501459D60_URL.sh" \
   --button=gtk-quit\:1 &
