#! /bin/bash
# Script generated by przyp.sh
#

p_IMG_FORUM=/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/71-BB6A0C0B-4018-4C94-AA64-BC1501459D60 POLSAT_Film 23-55 NASTĘPNE 8_PICTURE_FORUM.png
export DISPLAY=:0 && yad --title "Następne 48 godzin komedia sensacyjna USA 1990 ^^^" \
   --on-top --sticky --center \
   --borders=5 \
   --timeout=1200 \
   --timeout-indicator=bottom \
   --image "/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/71-BB6A0C0B-4018-4C94-AA64-BC1501459D60 POLSAT_Film 23-55 NASTĘPNE 8_PICTURE_FORUM.png" \
   --button=gtk-quit\:1 &
exit 0
