#! /bin/bash
# Script generated by przyp.sh
#

p_IMG_FORUM=/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/72-9F99313D-196E-4F7C-AD8D-F103DC00A230 Stopklatka 23-55 ŻYLETA 8_PICTURE_FORUM.png
export DISPLAY=:0 && yad --title "Żyleta film SF USA 1996 ^^" \
   --on-top --sticky --center \
   --borders=5 \
   --timeout=1200 \
   --timeout-indicator=bottom \
   --image "/home/rysio/Pobrane/PROGRAM_TV_ZEE/10_PRZDANE/72-9F99313D-196E-4F7C-AD8D-F103DC00A230 Stopklatka 23-55 ŻYLETA 8_PICTURE_FORUM.png" \
   --button=gtk-quit\:1 &
exit 0
